export const pages = {
  root: "/",
  home: "/home",
  library: "/library",
  podcasts: "/podcasts",
  premium: "/premium",
  help: "/help",
  download: "/download",
  search: "/search",
  signIn: "/auth/signin",
  signUp: "/auth/signup",
  signOut: "/auth/signout",
} as const;

export const styleConstants = {
  boxBorderRadius: 12,
  navIconSize: 35,
  defaultIconSize: 28,
  boxMargin: 4,
  collapsedLeftNavBox: 20,
  expandedLeftNavBox: 25,
  defaultPadding: 6,
  defaultRoundedBoxValue: 10,
  defaultLightBgHoverColor: "gray.200",
  defaultDarkBgHoverColor: "gray.800",
  boxLightColor: "gray.100",
  iconLightColor: "gray.600",
  textLightColor: "gray.800",
  textLinkLightColor: "gray.600",
  textLinkLightHoverColor: "gray.900",
  hoverTextLightColor: "black",
  actionsLightBgColor: "gray.300",
  popoverLightBgColor: "gray.100",
  boxBorderLightColor: "gray.400",
  boxDarkColor: "gray.900",
  iconDarkColor: "gray.300",
  textDarkColor: "gray.200",
  textLinkDarkColor: "gray.400",
  textLinkDarkHoverColor: "gray.200",
  hoverTextDarkColor: "white",
  actionsDarkBgColor: "gray.700",
  popoverDarkBgColor: "gray.700",
  boxBorderDarkColor: "gray.900",
} as const;
